### ISSUE TITLE
Add OpenAPI Schema for the REST API

### ISSUE THREAD

**Issue by mnhock** [enofex/naikan#6]
As part of improving our REST API documentation and providing a more standardized and comprehensive approach, we should integrate the OpenAPI Schema. The json should be under {schema}://{hostname}:{port}/api/public/schema.json and should be generated automatically.

**Comment by Chizobaonorh** [comment]
hello i would love to contribute to this.

**Comment by mnhock** [comment]
Hello @Chizobaonorh! Great to see your here! Thanks, for contributing! Do you need more information? This ticket refers to all controllers with starting with Api*Controller. At the moment they must be two of them.

**Comment by Chizobaonorh** [comment]
Hello i would love to contribute, i even started some contributions already, but to the general docs, i can make a pull request so you can see what i added to the documentation. And i would need to be guided hand-in-hand on how to go about running a request example and generating a response scheme to know what each response signifies. I would run that pull request now.

**Comment by Chizobaonorh** [comment]
hello @mnhock

**Comment by mnhock** [comment]
How to setup this project is described here: https://github.com/enofex/naikan/blob/main/DEVELOPING.md
Sample requests can be found here: https://github.com/enofex/naikan/blob/main/development/naikan-api.http
If the docker compose was started correctly you can see data in it and a configured valid bearer token as well. This you should use for the requests.

The PR is about generating the OpenAPI schema.json for the above described Controllers.

**Comment by Chizobaonorh** [comment]
Okay would work in it now.

**Comment by Chizobaonorh** [comment]
Hello i am encountering some issues setting up and starting the naikan application, I would need your assistance with that.

**Comment by Chizobaonorh** [comment]
@mnhock

**Comment by Chizobaonorh** [comment]
Hello, i am having an issue setting up to work on this project, from starting the naikan application and i would need assistance with that @mnhock

**Comment by Chizobaonorh** [comment]
from the part of automatically starting dependencies with docker compose

**Comment by mnhock** [comment]
You need docker desktop installed and then start the Spring Boot class described in the doc with the profile dev, -Dspring.profiles.active=dev as JVM parameter.

**Comment by Chizobaonorh** [comment]
okay will try this out.

**Comment by Chizobaonorh** [comment]
> You need docker desktop installed and then start the Spring Boot class described in the doc with the profile dev, -Dspring.profiles.active=dev as JVM parameter.

I can't locate this, i need help with this.
